config/routes.rb
AdTargeting::Application.routes.draw do
  root :to => 'keywords#index'

  resources :keywords do
    member do
      get :report
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      get "/keyword/:id", controller: 'tracking', action: 'show', as: 'keyword'
      get "/keyword/:id/click", controller: 'tracking', action: 'click', as: 'click_keyword'
    end
  end
end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  # == Accessors
  attr_accessible :name, :state_ids

  # == Associations
  has_many :targets
  has_many :states, through: :targets

  # == Validations
  validates :name, presence: true

  is_impressionable

  # == Instance Methods
  def click_rate
    return 0 if impressionist_count == 0
    (clicks_count.to_f / impressions_count).round(2)
  end

  def impressions_count
    impressions.where("message is null").count
  end

  def clicks_count
    impressions.where("message like '%click%'").count
  end
end

app/models/state.rb
class State < ActiveRecord::Base
  # == Accessors
  attr_accessible :name

  # == Associations
  has_many :targets
  has_many :keywords, through: :targets

  # == Validations
  validates :name, presence: true
end

app/models/target.rb
class Target < ActiveRecord::Base
  # == Accessors
  attr_accessible :keyword_id, :state_id

  # == Associations
  belongs_to :keyword
  belongs_to :state

  # == Validations
  validates :keyword, :state, presence: true
end

app/controllers/api/v1/tracking_controller.rb
class Api::V1::TrackingController < ApplicationController

  def show
    @keyword = Keyword.find(params[:id])
    impressionist(@keyword)

    render json: @keyword.attributes.merge(impressions_counts: @keyword.impressions_count)
  end

  def click
    @keyword = Keyword.find(params[:id])
    impressionist(@keyword, message: 'click')

    render json: @keyword.attributes.merge(click_counts: @keyword.clicks_count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @keywords }
    end
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @keyword }
    end
  end

  # GET /keywords/new
  # GET /keywords/new.json
  def new
    @keyword = Keyword.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @keyword }
    end
  end

  # GET /keywords/1/edit
  def edit
    @keyword = Keyword.find(params[:id])
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(params[:keyword])

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render json: @keyword, status: :created, location: @keyword }
      else
        format.html { render action: "new" }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /keywords/1
  # PUT /keywords/1.json
  def update
    @keyword = Keyword.find(params[:id])

    respond_to do |format|
      if @keyword.update_attributes(params[:keyword])
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword = Keyword.find(params[:id])
    @keyword.destroy

    respond_to do |format|
      format.html { redirect_to keywords_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/keywords/_form.html.erb
<% title "Ad Targeting System" %>

<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  Name: <%= f.text_field :name %><br />

  States : <%= f.select :state_ids,
                        options_from_collection_for_select(State.all, 'id', 'name', @keyword.states.map(&:id)),
                        {prompt: 'Please select US States'},
                        { multiple:true, size: 20} %><br />

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>

<table>
  <tr>
    <th>name</th>
    <th>states</th>
    <th></th>
    <th></th>
  </tr>

<% @keywords.each do |keyword| %>
  <tr>
    <td><%= link_to keyword.name, keyword %></td>
    <td>
      <ul>
          <% keyword.states.each do |state| %>
            <li><%= state.name %></li>
          <% end -%>
      </ul>

    </td>
    <td><%= link_to 'Report', keyword %></td>
    <td><%= link_to 'Edit', edit_keyword_path(keyword) %></td>
    <td><%= link_to 'Destroy', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>name</th>
    <th>states</th>
    <th>impressions</th>
    <th>clicks</th>
    <th>click rates</th>
  </tr>

  <tr>
    <td><%= link_to @keyword.name, @keyword %></td>
    <td>
      <ul>
          <% @keyword.states.each do |state| %>
            <li><%= state.name %></li>
          <% end -%>
      </ul>

    </td>

    <td><%= @keyword.impressions_count %></td>

    <td><%= @keyword.clicks_count %></td>

    <td><%= @keyword.click_rate %> </td>
  </tr>
</table>

<br />

<%= link_to 'New Keyword', new_keyword_path %>



<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdTargeting</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>